name: Test Build and Publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/ci.yml
      - .github/workflows/release.yml
      - .github/workflows/merge.yml
permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write
  actions: write
env:
  NX_BRANCH: ${{ github.head_ref || github.ref_name }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - run: npx nx run-many -t build --all

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract backend Docker metadata
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{env.IMAGE_NAME}}_api

      - name: Extract frontend Docker metadata
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{env.IMAGE_NAME}}_FE

      - name: Build affected projects
        run: npx nx run-many -t docker-build --all

      - name: Publish affected projects
        run: npx nx run-many -t docker-publish --all
